### ISSUE TITLE
New feature: bitcoin rate

### ISSUE THREAD

**Issue by geekingfrog** [CoucouInc/lambdaCoucou#7]
`λbitcoin` gives the current conversion rate bitcoin <-> usd.

**Comment by ordiclic** [comment]
A public REST API to  is available at https://api.cryptowat.ch/

Usage example:
`https://api.cryptowat.ch/markets/bitfinex/btcusd/price`
returns the following JSON data structure:
`{"result":{"price":8048.9},"allowance":{"cost":939943,"remaining":7999060057}}`

**Comment by geekingfrog** [comment]
Done in 23e01a3c5d071d1ec6fbefb22c47f7677243f76e
